### ISSUE TITLE
How to display the graphical interface?

### ISSUE THREAD

**Issue by gsycan** [lok-i/DRLPathPlanner#1]
Hello, I use pychram (python3.7) to run your code on the windows system, but there is no grid animation displayed, but the drawing result appears. How should this animation interface be set up?

**Comment by lok-i** [comment]
Hi @gsycan,
Could u elaborate? maybe the error msg or a screenshot ??

**Comment by gsycan** [comment]
well thanks,
I tried to run the MyNN code you provided, but the "Minigrid" image you mentioned in the introduction did not show up, but a drawing line chart.
I use pycharm under windows. After running MyNN and py, a line graph appears. Why is there no MiniGrid interface image?

**Comment by lok-i** [comment]
Hi @gsycan ,

I guess it is probably because the render_status variable (line number 100) is by default kept false to increase the speed of training. However if the line plot is showing up, it means the training is happening successfully and the rewards are logged.
In the next iteration of this (which I haven't released), I conducted experiments with stable baselines instead of my own PyTorch implementation. Also, I directly changed the reward function in the installed gym env file of the mini grid for my experiments. Hope my answer was helpful.
